version: '3'
services:
    webapp:
        container_name: webapp
        build: 
            context: ./
            dockerfile: ./webapp/Dockerfile
        expose:
            - "3000"

    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - "127.0.0.1:80:80"
        depends_on:
            - webapp

    mailhandler:
        container_name: mail_handler
        build:
            context: ./
            dockerfile: ./mailhandler/Dockerfile
        expose:
            - "25"
        depends_on:
            - nginx


